## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [5]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор размера 10, заполненный единицами

In [7]:
a1 = np.ones(10)
print(a1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать вектор размера 10, заполненный числом 2.5

In [8]:
a10 = np.linspace(2.5,2.5,10)
print(a10)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [11]:
a05 = np.eye(10)[4]
#a05[5] = 1
print(a05)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Развернуть вектор (первый становится последним)

In [4]:
v = np.arange(0,10)
print(v)
v = v[::-1]
print(v)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [6]:
v = np.arange(9).reshape(3,3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [7]:
v = np.nonzero([1,2,0,0,4,0])
print(v)

(array([0, 1, 4], dtype=int64),)


Создать 3x3 единичную матрицу

In [10]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Создать массив 3x3x3 со случайными значениями

In [12]:
v = np.random.random((3,3,3))
print(v)

[[[0.73361722 0.8842101  0.2997094 ]
  [0.53230829 0.13475055 0.94240025]
  [0.55141412 0.98207978 0.98423266]]

 [[0.45221613 0.04748577 0.21609297]
  [0.47128575 0.54055084 0.55908798]
  [0.84488316 0.13688607 0.1027442 ]]

 [[0.13851217 0.66501126 0.30273254]
  [0.39428739 0.68761085 0.27926345]
  [0.27473386 0.07582266 0.95056775]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [14]:
v = np.random.random(30)
print(v.mean())

0.5135063400905895


Перемножить матрицы 5x3 и 3x2

In [19]:
v = np.dot(np.ones((5,3)), np.ones((3,2)))
print(v)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [21]:
v = np.linspace(0,1,12)[1:-1]
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Заменить максимальный элемент на ноль

In [23]:
v = np.random.random(10)
print(v)
v[v.argmax()] = 0
print(v)

[0.29038805 0.88600662 0.69319607 0.38129797 0.7216463  0.25215197
 0.66976807 0.0323489  0.88826831 0.76143891]
[0.29038805 0.88600662 0.69319607 0.38129797 0.7216463  0.25215197
 0.66976807 0.0323489  0.         0.76143891]


Преобразовать массив из float в int

In [25]:
v = np.arange(10, dtype=np.float32)
print(v)
v = v.astype(np.int32, copy=False)
print(v)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [32]:
import scipy.spatial

v = np.random.random((10,2))
print(v)

print(scipy.spatial.distance.cdist(v,v))

[[0.24199872 0.10255388]
 [0.56744313 0.56811092]
 [0.61481952 0.52119905]
 [0.39594122 0.81917585]
 [0.32259547 0.36882779]
 [0.14088156 0.37106676]
 [0.38041716 0.85302076]
 [0.11071752 0.00135169]
 [0.79774228 0.82711845]
 [0.45557141 0.02129425]]
[[0.         0.56802942 0.56058819 0.73297021 0.27820429 0.28692131
  0.76312529 0.16576078 0.91315098 0.22850913]
 [0.56802942 0.         0.06667267 0.30405017 0.31569629 0.46987357
  0.34081129 0.72788344 0.34658707 0.55814313]
 [0.56058819 0.06667267 0.         0.36972677 0.32956319 0.49714876
  0.40626361 0.72412713 0.35643712 0.52465681]
 [0.73297021 0.30405017 0.36972677 0.         0.45628168 0.51561341
  0.0372354  0.86613446 0.40187956 0.80010674]
 [0.27820429 0.31569629 0.32956319 0.45628168 0.         0.1817277
  0.48763325 0.42418268 0.66014758 0.37210504]
 [0.28692131 0.46987357 0.49714876 0.51561341 0.1817277  0.
  0.53819789 0.37094353 0.79965565 0.47050027]
 [0.76312529 0.34081129 0.40626361 0.0372354  0.48763325 0.53819789


Случайно расположить p элементов в 2D массив

In [35]:
n = 10
p = 3
Z = np.zeros((n,n))
print(Z)
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [6]:
v = np.array([1, 2, 3, 4, 5])
print(v)

n = 3

z = np.zeros(len(v) + (len(v)-1)*(n))
z[::n+1] = v
print(z)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Найти наиболее частое значение в массиве

In [9]:
v = np.random.randint(0,10,50)
print(v)
print(np.bincount(v).argmax())

[3 4 1 5 6 2 9 8 9 7 8 3 9 9 8 3 4 0 2 2 6 5 2 6 5 0 0 8 7 4 4 3 8 5 8 8 7
 6 4 1 8 0 3 2 2 0 8 7 2 2]
8


Найти n наибольших значений в массиве

In [10]:
v = np.arange(10000)
print(v)
np.random.shuffle(v)
print(v)
n = 5

print (v[np.argpartition(-v,n)[:n]])

[   0    1    2 ... 9997 9998 9999]
[3699 9205 4267 ... 7945 7357 6489]
[9997 9999 9996 9998 9995]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [2]:
import pandas as pd

#food = pd.read_csv('D:\en.openfoodfacts.org.products.csv',sep='\t', engine='python')
food = pd.read_table('D:\en.openfoodfacts.org.products.tsv', low_memory=False)

Посмотреть первые 5 записей

In [20]:
print(food[:5])

            code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957 

Сколько наблюдений в наборе данных?


In [22]:
print(food['code'].count())

356001


Сколько столбцов в наборе данных?

In [23]:
print(len(food.columns))

163


Напечатайте все названия столбцов

In [24]:
print(food.columns)

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)


Какое название у 105 столбца?

In [25]:
print(food.columns[105])

-fructose_100g


Какой тип наблюдений в 105 столбце?

In [12]:
type(food.columns[105])

str

Как проиндексирован набор данных?

In [13]:
print(food.index)

RangeIndex(start=0, stop=356027, step=1)


Каково значение имени продукта в 19-м наблюдении?

In [11]:
print(food['product_name'][18])

Lotus Organic Brown Jasmine Rice


## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [14]:
import pandas as pd

chipo = pd.read_table('D:\chipotle.tsv', low_memory=False)

Как много продуктов стоят более чем $10.00?

In [40]:
print(chipo[chipo['item_price'].str.replace('$','').astype('float64') >10])

      order_id  quantity           item_name  \
4            2         2        Chicken Bowl   
5            3         1        Chicken Bowl   
7            4         1       Steak Burrito   
13           7         1        Chicken Bowl   
23          12         1     Chicken Burrito   
39          19         1       Barbacoa Bowl   
42          20         1        Chicken Bowl   
43          20         1       Steak Burrito   
45          21         1     Chicken Burrito   
52          24         1     Chicken Burrito   
57          26         1      Veggie Burrito   
58          27         1       Barbacoa Bowl   
62          28         1         Veggie Bowl   
68          30         1     Chicken Burrito   
79          35         1  Chicken Soft Tacos   
90          40         1          Steak Bowl   
91          40         1          Steak Bowl   
93          41         1    Carnitas Burrito   
97          43         1       Carnitas Bowl   
123         54         1        Chicken 

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [46]:
print(chipo[['item_name','item_price']])

                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
5                              Chicken Bowl    $10.98 
6                             Side of Chips     $1.69 
7                             Steak Burrito    $11.75 
8                          Steak Soft Tacos     $9.25 
9                             Steak Burrito     $9.25 
10                      Chips and Guacamole     $4.45 
11                     Chicken Crispy Tacos     $8.75 
12                       Chicken Soft Tacos     $8.75 
13                             Chicken Bowl    $11.25 
14                      Chips and Guacamole     $4.45 
15    Chips and Tomatillo-Green Chili Salsa     $2.39 
16                          Chicken Burrito     $8.49 
17        

Отсортировать по имени предмета

In [57]:
print(chipo.sort_values(by=['item_name'], ascending=False))

      order_id  quantity          item_name  \
3889      1559         2  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
738        304         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
4573      1818         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
4261      170

Сколько было заказано самого дорогого предмета?

In [59]:
chipo.loc[chipo['item_price'].str.replace('$','').astype('float64').idxmax()]['quantity']

15

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [66]:
chipo.loc[chipo['item_name'] == 'Veggie Salad Bowl']['order_id'].count()

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [71]:
chipo.loc[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]

order_id  quantity    item_name choice_description item_price
18           9         2  Canned Soda           [Sprite]     $2.18 
51          23         2  Canned Soda     [Mountain Dew]     $2.18 
162         73         2  Canned Soda        [Diet Coke]     $2.18 
171         76         2  Canned Soda  [Diet Dr. Pepper]     $2.18 
350        150         2  Canned Soda        [Diet Coke]     $2.18 
352        151         2  Canned Soda        [Coca Cola]     $2.18 
698        287         2  Canned Soda        [Coca Cola]     $2.18 
700        288         2  Canned Soda        [Coca Cola]     $2.18 
909        376         2  Canned Soda     [Mountain Dew]     $2.18 
1091       450         2  Canned Soda       [Dr. Pepper]     $2.18 
1092       450         2  Canned Soda        [Coca Cola]     $2.18 
1944       787         2  Canned Soda       [Dr. Pepper]     $2.18 
2135       859         2  Canned Soda        [Diet Coke]     $2.18 
2235       901         4  Canned Soda           [Sprite]     $4.36 
2905      1156         2  Canned Soda        [Coca Cola]     $2.18 
2906      1156         2  Canned Soda           [Sprite]     $2.18 
3152      1258         2  Canned Soda       [Dr. Pepper]     $2.18 
3364      1349         2  Canned Soda        [Coca Cola]     $2.18 
3592      1440         2  Canned Soda        [Diet Coke]     $2.18 
3866      1550         2  Canned Soda     [Mountain Dew]     $2.18